import type { IhramProhibition } from "@/types/umrah";

export const IHRAM_PROHIBITIONS: IhramProhibition[] = [
  {
    id: "sewn-clothing",
    titleAr: "لبس المخيط",
    titleEn: "Wearing sewn/fitted clothing",
    descriptionAr: "يحرم على الرجل لبس الملابس المخيطة المفصلة على الجسم",
    descriptionEn: "Men must not wear any sewn or tailored clothing that fits the body",
    appliesTo: "men",
    icon: "shirt",
  },
  {
    id: "head-covering",
    titleAr: "تغطية الرأس",
    titleEn: "Covering the head",
    descriptionAr: "يحرم على الرجل تغطية رأسه بملاصق كالطاقية والغترة",
    descriptionEn: "Men must not cover their head with fitted coverings like caps or headscarves",
    appliesTo: "men",
    icon: "hard-hat",
  },
  {
    id: "niqab",
    titleAr: "لبس النقاب",
    titleEn: "Wearing the niqab (face veil)",
    descriptionAr: "تحرم المرأة من لبس النقاب، ويجوز لها إسدال الخمار على وجهها عند مرور الرجال",
    descriptionEn:
      "Women must not wear the niqab but may drape a loose cloth over the face when men pass",
    appliesTo: "women",
    icon: "eye-off",
  },
  {
    id: "gloves",
    titleAr: "لبس القفازين",
    titleEn: "Wearing gloves",
    descriptionAr: "تحرم المرأة من لبس القفازين حال الإحرام",
    descriptionEn: "Women must not wear gloves during Ihram",
    appliesTo: "women",
    icon: "hand",
  },
  {
    id: "perfume",
    titleAr: "استعمال الطيب",
    titleEn: "Using perfume or scented products",
    descriptionAr: "يحرم استعمال الطيب في البدن أو الثوب بعد الإحرام",
    descriptionEn: "Using perfume on the body or clothing after entering Ihram is prohibited",
    appliesTo: "both",
    icon: "spray-can",
  },
  {
    id: "cut-hair",
    titleAr: "إزالة الشعر",
    titleEn: "Cutting or removing hair",
    descriptionAr: "يحرم إزالة شعر الرأس أو البدن بأي وسيلة",
    descriptionEn: "Removing hair from the head or body by any means is prohibited",
    appliesTo: "both",
    icon: "scissors",
  },
  {
    id: "cut-nails",
    titleAr: "تقليم الأظافر",
    titleEn: "Trimming nails",
    descriptionAr: "يحرم تقليم أظافر اليدين أو الرجلين",
    descriptionEn: "Trimming fingernails or toenails is prohibited",
    appliesTo: "both",
    icon: "minus",
  },
  {
    id: "hunting",
    titleAr: "صيد البر",
    titleEn: "Hunting land animals",
    descriptionAr: "يحرم صيد الحيوانات البرية أو المساعدة في ذلك",
    descriptionEn: "Hunting land animals or assisting in hunting is prohibited",
    appliesTo: "both",
    icon: "target",
  },
  {
    id: "marriage",
    titleAr: "عقد النكاح",
    titleEn: "Marriage contract or proposal",
    descriptionAr: "يحرم عقد النكاح أو الخطبة حال الإحرام",
    descriptionEn: "Contracting a marriage or proposing during Ihram is prohibited",
    appliesTo: "both",
    icon: "heart",
  },
  {
    id: "relations",
    titleAr: "الجماع",
    titleEn: "Sexual relations",
    descriptionAr: "يحرم الجماع ودواعيه حال الإحرام",
    descriptionEn: "Sexual relations and their precursors are prohibited during Ihram",
    appliesTo: "both",
    icon: "x-circle",
  },
  {
    id: "uprooting",
    titleAr: "قطع نبات الحرم",
    titleEn: "Uprooting trees or plants in Haram",
    descriptionAr: "يحرم قطع أشجار الحرم ونباته",
    descriptionEn:
      "Cutting or uprooting trees and plants within the Haram boundaries is prohibited",
    appliesTo: "both",
    icon: "tree-pine",
  },
];
