import type { MiqatPoint } from "@/types/umrah";

export const MIQAT_POINTS: MiqatPoint[] = [
  {
    id: "dhul-hulayfah",
    nameAr: "ذو الحليفة",
    nameEn: "Dhul Hulayfah",
    alternateNameAr: "أبيار علي",
    alternateNameEn: "Abyar Ali",
    distanceFromMakkahKm: 450,
    fromDirections: ["madinah"],
    isInsideMakkah: false,
  },
  {
    id: "juhfah",
    nameAr: "الجحفة",
    nameEn: "Al-Juhfah",
    alternateNameAr: "رابغ",
    alternateNameEn: "Rabigh",
    distanceFromMakkahKm: 183,
    fromDirections: ["syria", "egypt", "maghreb"],
    isInsideMakkah: false,
  },
  {
    id: "yalamlam",
    nameAr: "يلملم",
    nameEn: "Yalamlam",
    distanceFromMakkahKm: 120,
    fromDirections: ["yemen"],
    isInsideMakkah: false,
  },
  {
    id: "qarn-al-manazil",
    nameAr: "قرن المنازل",
    nameEn: "Qarn al-Manazil",
    alternateNameAr: "السيل الكبير",
    alternateNameEn: "Al-Sayl al-Kabir",
    distanceFromMakkahKm: 75,
    fromDirections: ["najd", "riyadh"],
    isInsideMakkah: false,
  },
  {
    id: "dhat-irq",
    nameAr: "ذات عرق",
    nameEn: "Dhat Irq",
    distanceFromMakkahKm: 100,
    fromDirections: ["iraq", "east"],
    isInsideMakkah: false,
  },
  {
    id: "tanim",
    nameAr: "مسجد عائشة",
    nameEn: "Masjid Aisha",
    alternateNameAr: "التنعيم",
    alternateNameEn: "Tan'im",
    distanceFromMakkahKm: 8,
    fromDirections: ["makkah"],
    isInsideMakkah: true,
  },
];
